### ISSUE TITLE
Při výběru libovolné pobočky se objednávka uloží s pobočkou Brno

### ISSUE THREAD

**Issue by petaak** [ulozenka/prestashop-1-5#11]
Používáme modul pro prestashop 1.6.9, ale nefunguje nám správně. Modul uloží vždy jen pobočku Brno, ať se v košíku vybere jakákoli.
www.babyday.cz
Používáme modul onepagecheckout, ale v tom by neměl snad být problém.

**Comment by cilecek** [comment]
www.babyday.cz
verze 1.4beta funguje správně

**Comment by MilanFrybert** [comment]
Dobrý den, děkuji za informaci, issue tedy uzavírám jako vyřešeno.
