### ISSUE TITLE
Cena s DPH

### ISSUE THREAD

**Issue by iglous** [ulozenka/prestashop-1-5#13]
Dobrý den,

mohu se zeptat jakým způsobem lze docílit aby zobrazovaná cena s DPH
byla v celých korunách? Pro názornost uvedu příklad. Když bude chtít
cenu s DPH 45 Kč, zadám v nastavení modulu cenu bez DPH 37,190082 Kč a v
košíku se pak zobrazuje cena s DPH 44,77 Kč. Zkoušel jsem i jiné částky
a zadat všechna desetinná místa.

David Švehla

**Comment by MilanFrybert** [comment]
Dobrý den, 

pro oddělení desetiného místa prosím použijte místo čárky tečku - 37.192 Kč. Poté již nastavení ceny funguje správně.
