### ISSUE TITLE
Po aktualizaci modulu z v. 1.2. na verzi 1.3. se nedá dostat do Obejdnávky/Ulozenka

### ISSUE THREAD

**Issue by petaak** [ulozenka/prestashop-1-5#15]
Dobrý den,
po aktualizaci modulu Ulozenka z v. 1.2. na verzi 1.3. se nedostanu do Obejdnávky/Ulozenka.
Poradíte prosím?

**Comment by MilanFrybert** [comment]
Dobrý den, 

prosím zkuste aktualizovat na nejnovější verzi modulu.

**Comment by MilanFrybert** [comment]
Dobrý den, vzhledem k tomu že tazatel již dále nereaguje, uzavírám tento problém jako neaktuální.
