### ISSUE TITLE
Umožnit definovat cenu v závislosti na platební metodě

### ISSUE THREAD

**Issue by martinvenus** [ulozenka/prestashop-1-5#16]
Bylo by pěkné, kdyby bylo možné definovat cenu v závislosti na platební metodě. Např. Jinou cenu pro platbu na dobírku a jinou cenu pro platebu bez dobírky.

**Comment by prestahost** [comment]
Dobrý den,

uloženka je dopravce a za ní jsou ještě moduly platby - cenu lze navýšit 
modulem dobírky, takže tady to velký smysl nemá

a rád bych vás požádal o odpověď na můj předchozí email


Dne 18.2.2015 v 17:26 Martin Venuš napsal(a):

**Comment by MilanFrybert** [comment]
Tito issue uzavírám.
