### ISSUE TITLE
pokus o spuštění cron -> Parse error: syntax error...

### ISSUE THREAD

**Issue by cilecek** [ulozenka/prestashop-1-5#17]
při pokusu o spuštění cron scriptu vrací error

`Parse error: syntax error, unexpected T_CONST in /var/www/virtual/babyday.cz/htdocs/modules/ulozenka/cron.php on line 16`

PS 1.4.0.9
Uloženka modul verze 1.4beta

**Comment by MilanFrybert** [comment]
Dobrý den, 

prosím o informaci zda je chyba stále aktuální nebo se povedlo problém vyřešit. Děkuji

**Comment by MilanFrybert** [comment]
Dobrý den, vzhledem k nedostatku informací a žádné reakci na dotaz tuto issue uzavírám.
