### ISSUE TITLE
Podrobnosti o pobočce odeslané na e-mail

### ISSUE THREAD

**Issue by michalucen** [ulozenka/prestashop-1-5#18]
V e-mailu odeslaném na zákazníkovu adresu s podrobnostmi o vybrané pobočce se v některých případech zobrazí u některých údajů hodnota "array" (viz. screenshot) Je to pravděpodobně v případech, kdy daný údaj chybí. Není možné udělat opravu, že když daný údaj chybí, nezobrazí se nic? "Array" nevypadá příliš dobře. Případně pokud jde udělat nějaká manuální oprava, budu rád za instrukce.

Děkuji.

**Comment by MilanFrybert** [comment]
Dobrý den, 

bohužel se mi nepodařilo na našem testovacím shopu chybu zopakovat. Je možné poskytnout více informací? Protože nevidím ani přiložený screenshot nevím které údaje v e-mailu nejsou. Děkuji

**Comment by MilanFrybert** [comment]
Dobrý den, vzhledem k tomu že tazatel dále nereaguje a nedostatku informací uzavírám tuto issue jako neaktuální

**Comment by miroslavmurin** [comment]
Dobrý deň,
poprosil by som o otvorenie tohoto ticketu.
Problémom je, že nie vo všetkých prípadoch vráti API k pobočke XML tag MAP a v takomto prípade sa vypíše ARRAY namiesto mapy. Viď screenshoty. Uprávu som na svojom webe spravil následujúcu:

public function getPobockaByZkratka($code, $use_default = 1) {
.
.
.
if ($pobocka['shortcut'] == $code) {
if (!$pobocka[map])
                      $pobocka[map] = '<iframe width="600" height="400" 
                        frameborder="0" scrolling="no" marginheight="0" 
                        marginwidth="0" 
                        src="http://maps.google.cz/?q='.$pobocka['gps']['latitude'].','.$pobocka['gps']['longitude'].'&source=embed&hl=cs&output=embed">
                        </iframe>'; 
 return $pobocka;
                }
![ulozenka-pobocky-array-01](https://cloud.githubusercontent.com/assets/12099297/8024050/65aee74a-0d25-11e5-86a0-45b7ecfe3ac9.png)

**Comment by MilanFrybert** [comment]
Dobrý den, na základě Vašeho požadavku issue otevírám, zjistíme kde je problém.

**Comment by MilanFrybert** [comment]
Problém by měl být vyřešen, ticket uzavírám.
