### ISSUE TITLE
Zobrazeni ruznych pobocek v CZ a SK jazykove verzi eshopu

### ISSUE THREAD

**Issue by evas123** [ulozenka/prestashop-1-5#19]
Dobry den,
> Jiz dlouho se zabýváme problémem rozdeleni modulu ulozenka pro CZ a SK 
> verzi našeho eshopu. Nas IT vždy narazi na problém při duplikaci 
> modulu. Mozna nam poradite.
>
> Chteli bychom aby se v CZ verzi zobrazovali jen pobočky ulozenka a 
> parcel shop pro ČR a ve SK verzi jen pobočky pro Slovensko. Nastaveni 
> modulu to neumoznuje. Duplikace modulu, aby byl funkcni se nam nepodarila.
> Jak by se dal tento problém vyresit?
> Nastaveni zobrazovani všech poboček pro obe jazykove verze eshopu mi 
> prijde pro zakazniky velice zahlcujici:)

S pozdravem
Vlasakova

**Comment by prestahost** [comment]
Dobrý den,

duplikace se opravdu nepodaří, ale mělo by být možné uložit odděleně 
nastavení v rámci multishopu

Václav Mach

Dne 20.4.2015 v 18:27 evas123 napsal(a):

**Comment by evas123** [comment]
A to se prosim provadi jak?

**Comment by michalucen** [comment]
Mám stejný problém, zobrazení tolika poboček ze dvou států v jednom seznamu, navíc bez žádné struktury je velmi nepřehledné. Z tohoto důvodu máme DPD Parcelshop pouze pro Slovensko. Multishop to bohužel neřeší, respektive předělávání eshopu na multishop kvůli modulu Uloženky je nesmysl.

Ocenil bych buď možnost rozdělení dopravce podle států, naklonování modulu nebo alespoň strukturování listu poboček podobně jak je to na webu Uloženky - tedy s nějakým "podnadpisem" že se jedná o pobočky DPD Parcel shop SK, DPD Parcel shop CZ, pobočky Uloženky CZ apod.

**Comment by MilanFrybert** [comment]
Dobrý den, po dohodě s vývojářem modulu bude toto umožněno v další verzi na které se aktuálně pracuje.  Hned jak budou tyto úpravy hotové bude zde na GitHubu ke stažení nová verze.

**Comment by evas123** [comment]
Dobry den,
nevim, zda hledam spravne a ve spravnou dobu, ale kde a kdy by mohla byt k dispozici verze nove ulozenky se zapracovanymi vyse uvedenym pozadavky?
Dekuji za info.

**Comment by MilanFrybert** [comment]
Dobrý den, jako reálný termín se v současné době jeví konec léta 2016.  V modulu bude zapracována možnost rozdělení poboček na ČR a SK, včetně volby využívaných poboček a přepravních služeb.

**Comment by mir69** [comment]
Dobrý den, téma uzavřeno, ale - pane Frýberte - dopadlo to nějak? Která verze modulu toto již podporuje,a / resp. pro kterou verzi PS? Děkuji.

**Comment by Hadamcik** [comment]
Dobrý den, pro současnost je modul do Prestashopu pro implementaci Uloženky ze strany Uloženky dlouhodobě nepodporován. Je pravděpodobné, že budeme dělat novou verzi, ale aktuálně máme jiné priority pro vývoj.

**Comment by mir69** [comment]
Dobrý den, děkuji za odpověď. Takže jestli jsem to dobře pochopil - jak se píše v létě 2015- "reálný termín se v současné době jeví konec léta 2016" - k tomu vůbec nedošlo? Děkuji.

**Comment by Hadamcik** [comment]
Nedošlo. Historický modul byl vyvíjen externě mimo Uloženku. S autory už velmi dlouho nejsme v kontaktu a bohužel nemáme dostatek kapacity pro vývoj nového modulu (jelikož od doby kdy byl podporovaný starý prošla Uloženka velkou řadou změn díky kterým je téměř nemožné jeho použití). Pevně věřím, že jednou modul do Prestashopu zase vyvineme ovšem pro teď si neodvažuji říci termín, jelikož se soustředíme na vývoj s větší prioritou především pro zlepšení služeb našim zákazníkům.

Omlouvám se za způsobené komplikace.

**Comment by mir69** [comment]
Děkuji za Vaši odpověď. Mě tedy naštěstí modul 1.4.1 na Prestě 1.5.4.1 jakš takš jede :-), ale pobočky jsou ze začátku okna rozházené, neseřazené, nejsou právě rozdělené na CZ a aSK, úplně dole pod SK je schovaných asi 6 pražských poboček...  Škoda, mě osobně šlo asi o 80% zasílání pře Uloženku dolů... Tak snad... někdy v budoucnu.

**Comment by PrestaShopExpert** [comment]
Dobrý den, 
umím vám upravit modul Uloženka jak požadujete.
Už jsem to pro klienty dělal, není problém např.:
- seřadit pobočky dle abecedy
- zobrazovat jen pobočky vybraného typu (Uloženka, Uložneka frenčíza, DPD Pickup)
- upravit zobrazení výpisu poboček
(viz. např. [www.doktorkaromana.cz](https://www.doktorkaromana.cz))

Mohu dodělat i:
- ve výpisu identifikovat typ pobočky (Uloženka, Uloženka frenčíza, DPD Pickup)
- pro CZ zákazníky zobrazovat jen CZ pobočky a opačně pro SK
- seskupit pobočky dle krajů (nebo přidat rozbalovací seznam s kraji)

Pracuji také na portaci modulu pro PrestaShop 1.7.


Pokud máte o některé tyto úpravy zájem, prosím neváhejte mě kontaktovat.


Petr Pánek
▪︎ implementace a podpora PrestaShop e-shopů, 
▪︎ optimalizace konverzního poměru e-shopů (CRO/UX),
▪︎ specialista na cenové srovnávače,
▪︎ certifikovaný Heureka specialista

+420 602 444 294 
petr@prestashop.expert
[www.prestashop.expert](https://www.prestashop.expert)

**Comment by mir69** [comment]
Dobrý den pane Pánku,
děkuji za Vaši zprávu.
Ozvu se Vám.
