### ISSUE TITLE
Kolize s platebním modulem PaySec

### ISSUE THREAD

**Issue by ulozenka** [ulozenka/prestashop-1-5#2]
Nainštaloval som si na eshop (prestashop 1.5.6.1) Váš modul pre uloženku. Ale v kombinácii z platbou cez paysec sa neuloží uloženka v objednávke kam má. Viete poradiť pri tomto probléme?

**Comment by MilanFrybert** [comment]
Dobrý den, 

prosím o informaci zda je problém stále aktuální nebo zda je již vyřešen. Děkuji
