### ISSUE TITLE
Spatny update ceny

### ISSUE THREAD

**Issue by miroslavmurin** [ulozenka/prestashop-1-5#20]
Dobry den,
Mám nainštalovaný Prestashop vo verzii 1.6.0.11 a modul Uloženka, a onepagecheckout proces objednávok.
Pri výbere modulu a adresy pre doručenie sa mi zmení cena za poštovné v inom riadku/module než je riadok pre Uloženku.

Problem bude pravdepodobne v javascripte pri vybere spravneho elementu pre zmenu hodnoty.

.success(function( data ) {
    console.log(data);    
    if(data['onepageactive'] == 1)
         var prices=$('td.carrier_price');
    else if(data['version'] == 160)
        var prices=$('td.delivery_option_price');
    else
        var prices=$('.delivery_option_price');      
   
   $(prices[num]).text(data['cena']);
   if (data['refresh'] == 1) {
       if(data['opc'] ==1 && ulozenkaActive) {
         $("#HOOK_PAYMENT").html(data['platba'] );
       }
   
    if(data['allow'] == 1)
      $("#pobockadetail").show();  
   else
      $("#pobockadetail").hide();
   } 
   if(data['onepageactive'])
       updateCarrierSelectionAndGift();
});

![ulozenka github modul problem 01](https://cloud.githubusercontent.com/assets/12099297/7318909/bf3f1530-ea90-11e4-9552-d3057b6fd81d.png)
![ulozenka github modul problem 02](https://cloud.githubusercontent.com/assets/12099297/7318908/bf3e1324-ea90-11e4-861d-8f55ffc96ef0.png)

**Comment by MilanFrybert** [comment]
Dobrý den, na odstraněné tohoto problému již pracuje vývojář modulu. Ihned jak bude otestovaný modul k dispozici, dám informaci že je ke stažení nová verze. Děkujeme za report problému.

**Comment by MilanFrybert** [comment]
Nove verze modulu je již k dispozici, tato chyba je v ní opravena.
