### ISSUE TITLE
změna stavu objednávky po exportu

### ISSUE THREAD

**Issue by cilecek** [ulozenka/prestashop-1-5#22]
při exportu objednávky do systému uloženka by se měla objednávka automaticky přepnout na stav "odesláno uloženka"
stav objednávky, na který se bude přepínat by se měl dát nastavit v konfiguraci modulu
---
používám verzi 1.4b v PS1.6.0.14

**Comment by MilanFrybert** [comment]
Dobrý den, 

ve Vašem dotazu spojujete dohromady dvě rozdílné věci - export objednávek a stav objednávky. 

1) Při exportu objednávek do Uloženky dojde k označení objednávek jako exportovaných (zelená fajfka v seznamu objednávek kolonka exportováno). 

2) V současné verzi modulu lze nastavit změnu stavu zásilky pouze pro doručeno - Uloženka doručeno. Ve vývoji je další verze modulu Uloženka která bude načítat všechny stavy zásilky tak jak jsou vidět v systému Uloženky.

**Comment by cilecek** [comment]
dobrý den,
asi jsem se špatně vyjádřil. 

přijde nová objednávka, která má stav např. "připraveno k odeslání", po exportování do uloženky by se ale stav objednávky měl přepnout tak, aby bylo na první pohled patrné, že je objednávka odeslána. teď po exportu objednávek do uloženky musíme všechny objednávky po jedné přepnout na "odesláno"

statusy by měly být alespoň připraveno k odeslání -> odesláno uloženka -> doručeno uloženka,
teď je to připraveno k odeslání -> doručeno uloženka

**Comment by MilanFrybert** [comment]
Dobrý den, 

ano, nyní již si rozumíme. Řešení bude provedno pomocí bodu 2 v mém předchozím komentáři. 
Objednávka po exportu na Uloženku se přepne do stavu "Čekáme na doručení" a poté s každou změnou jejího stavu se tato změna projeví i změnou statusu v Prestashopu. 
Na úpravě se pracuje, proto Vás chci požádat o strpení, ihned jak bude nová verze modulu k dispozici zveřejníme ji zde na GitHubu.

**Comment by cilecek** [comment]
super, díky moc... zavírám
