### ISSUE TITLE
Nefunkční .csv export

### ISSUE THREAD

**Issue by ASWF** [ulozenka/prestashop-1-5#25]
zdravím,

mám prestu ve verzi 1.6.0.8, modul ve verzi 1.4.1, když chci v sekci objednávky exportovat, tak při exportu mi to hlásí chybu

Export se nezdařilstdClass::__set_state(array( 'code' => 401, '_links' => stdClass::__set_state(array( )), 'data' => array ( ), 'errors' => array ( 0 => stdClass::__set_state(array( 'code' => 1001, 'description' => 'X-Key header missing. You have to send your api key in the X-Key http header of your request.', )), ), )) 

v případě, že si doplním api key do pole v modulu, tak stejně mi to hodí:
Export se nezdařilstdClass::__set_state(array( 'code' => 401, '_links' => stdClass::__set_state(array( )), 'data' => array ( ), 'errors' => array ( 0 => stdClass::__set_state(array( 'code' => 1001, 'description' => 'Invalid shop - key combination.', )), ), )) 

klíč jsem preventivně znovu vygeneroval, přesto nefunguje, ale pro mě propojení přes API není tak podstatné, ale CSVčko ušetří čas :)

-------------------------
Dám to do jednoho, rozjíždím druhý eshop na prestě 1.6.1, modul 1.4.1, zatím to mám v testovací fázi, vše funguje až opět na export, tentokrát se v sekci objednávky do uloženky ani nedostanu, hodí to
Špatný SQL dotaz
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'pobocka_name`, a.`date_add` AS `date_add`, date_exp` AS `date_exp`, exported` AS' at line 2

Jede to na stejném VPSku jako ten shop výše.

Předem děkuji za rady

**Comment by MilanFrybert** [comment]
Dobrý den, 

ty první 2 problémy souvisí se špatným API klíčem, respektive špatnou kombinací ID obchodu a API klíč. Zkontrolujte prosím správnost API klíče - klíč si vygenerujete v partnerské sekci Uloženky, záložka mé obchody / nastavení obchodu / nastavit klíč pro API. ID obchodu naleznete v záložce mé obchody u konkrétního obchodu. 

Druhý problém lze vyřešit následujícím způsobem: 

v souboru AdminOrderUlozenka.php
řádek 40
$this->explicitSelect = false;

Násladně by to již mělo fungovat bez problémů.

**Comment by ASWF** [comment]
dobrý den, děkuji, obojí funguje

**Comment by MilanFrybert** [comment]
Děkuji, za informaci, jsem rád že se problém podařilo vyřešit.
