### ISSUE TITLE
návrh: zvolení dopravce po výběru pobočky

### ISSUE THREAD

**Issue by ASWF** [ulozenka/prestashop-1-5#27]
zdravím,

celkem dost se mi začínají hromadit zákazníci, co při výběru dopravce si vyberou z roletky pobočku Uloženky, ale jako dopravce ho nezvolí ("nezaškrknou"), protože zvolením v roletce to považují za hotovou záležitost aniž by se to obtěžovali zkontrolovat a pak nikdo u nás nevíme, kam to chtěli zaslat, protože pro nás si zvolili defaultního dopravce. Nevím, jestli defaultně to modul umí a mě to s něčím jenom koliduje, ale pokud to není, tak jistě nebudu jediný, kdo by o tuto úpravu poprosil :)

Děkuji

**Comment by MilanFrybert** [comment]
Dobrý den, 

bohužel si nejsem jistý zda toto dokážeme nějak ovlivnit. Nutnost zatrhnout zvolenou dopravu je výchozí chování Prestashopu a nejsem si jistý nakolik je toto možno ovlivnit. Zkusím ale probrat s prgramátorem modulu. Děkuji za návrh na zlepšení. 

Milan Frýbert

**Comment by ASWF** [comment]
Dobrý den,

vím, že konkurenční Zásilkovna toto ve svém modulu měla, tak možná nějakou kóderskou inspiraci najdete u nich, z pohledu zákazníka ty moduly v dopravě vypadají totožně a možná jsou někteří kvůli tomu naučení, že si zvolí pobočku a slepě pokračují dál.

V.K.

**Comment by MilanFrybert** [comment]
Dobrý den, děkuji mnohokrát za informaci, určitě to zvážíme a pokusíme se zašlenit do další verze modulu.
