### ISSUE TITLE
V poznámce se nezobrazí vybraná pobočka 

### ISSUE THREAD

**Issue by michalucen** [ulozenka/prestashop-1-5#3]
Po instalaci modulu a první objednávce je vše v pořádku, zobrazí se pobočka v poznámce u objednávky. U dalších objednávek se ovšem nezobrazí, v poznámce není nic a tedy není možné určit, kam odeslat zásilku.

Zkoušel jsem různé varianty (měnit typ platby apod.) ale bez výsledku.

**Comment by MilanFrybert** [comment]
Bohužel se mi chybu nepodařilo reprodukovat, je možné poskytnout k tomuto problému další informace? Děkuji.

**Comment by michalucen** [comment]
Dobrý den, s novou verzí modulu už se mi chyba neobjevuje a zatím vše běží v pořádku.

**Comment by MilanFrybert** [comment]
Dobrý den, 

děkuji za informaci, issue tedy uzavírám jako vyřešeno.
