### ISSUE TITLE
Nelze dopravce rozdělit na ČR a SR

### ISSUE THREAD

**Issue by michalucen** [ulozenka/prestashop-1-5#4]
Při použití v eshopu s dodáním na Slovensko nelze rozdělit pobočky na české a slovenské, tedy vzniká problém, že čeští zákazníci "vidí" a mohou si vybrat ze slovenských poboček a naopak.

Nebylo by od věci také oddělit pobočky Uloženky a DPD Parcel Shopu do dvou dopravců, seznam v drop-downu je velmi dlouhý a nepřehledný

**Comment by MilanFrybert** [comment]
Dobrý den, 

tato funkčnost bude zahrnuto v další verzi modulu který je momentálně ve vývoji.
