### ISSUE TITLE
Nezobrazující se pobočky v košíku

### ISSUE THREAD

**Issue by ChemicalGuys** [ulozenka/prestashop-1-5#5]
Dobrý den,
mám obchod na Prestě v 1.5.4.1, nainstaloval jsem modul ze souborů zde na GH (ale stejný výsledek jsem měl i u starších verzí modulů 1.1 i 1.2 stažených přímo z uloženky), problém je, že se mi v košíku nezobrazuje výběr poboček. Instalace mi proběhne v pořádku, v DB se vytvoří tabulky, v modulech se vytvoří pozice, viz screenshoty níže.  CHMOD mám nastavený 755/644.

Zároveň mám na eshopu sprovozněný modul pro Zásilkovnu s výběrem poboček a ten funguje bez problémů.

Update na vyšší verzi presty bohužel není možný.

screenshoty:
nanowax.cz/GHulozenka.zip

děkuji za rady

**Comment by MilanFrybert** [comment]
Dobrý den, bohužel tento problém se mi nepodařilo reproduktovat a soubor zip již také není dostupný. Pokud je problém stále aktuální, je možno poskytnout dodatečné informace? Děkuji

**Comment by MilanFrybert** [comment]
Dobrý den, vzhledem k tomu že tazatel dále nereaguje a nemáme dostatek informací pro další řešení, uzavírám problém jako neaktuální.
