### ISSUE TITLE
odoslanie miesta 2x

### ISSUE THREAD

**Issue by tozi** [ulozenka/prestashop-1-5#7]
Dobrý deň,
nainštaloval som si Váš modul na eshop postavený na prestashop 1.5.6.1.
Problém je po potvrdení objednávky. Miesto doručenia sa odošle 2x z rôznymi údajmi o
mieste (jedno miesto ktoré je v priebehu objednávky prednastavené v selecte
a druhý z tým miestom ktoré si zákazník skutočne vybral). Príde aj mne ako
zákazníkovy 2x email z rôznymi údajmi o mieste...

Viete mi poradiť kde by mohol byť problém?

Ďakujem

**Comment by MilanFrybert** [comment]
Dobrý den, 

vzhledem k dlouhé době bez reakce uzavírám toto issue a považuji za vyřešené.
