### ISSUE TITLE
Modul nerespektuje nastavení, zda obchod je/není plátcem DPH. 

### ISSUE THREAD

**Issue by petaak** [ulozenka/prestashop-1-5#8]
Pokud je eshop nastaven jak neplátce DPH tak to Váš modul nebere v potaz a pomocí skriptu ulozenka-ajax.php vždy dopisuje k ceně (s DPH) - vyřešil jsem úpravou tohoto php, ale nešlo by do budoucí verze opravit - určitě se to dá v nastaveních eshopu najít jestli je nebo není plátce DPH.

**Comment by MilanFrybert** [comment]
Tato chyba byla již odstraněna, ticket uzavírám.
