### ISSUE TITLE
Neaktualizuje se cena za přepravu.

### ISSUE THREAD

**Issue by petaak** [ulozenka/prestashop-1-5#9]
V připadě one page checkout se neaktualizuje cena za dopravu v souhrnu objednávky a zůstáva tam cena defaultní, problém je když máte nastavenou jinou cenu pro různé místa vyzvednutí.

**Comment by MilanFrybert** [comment]
Dobrý den, 

prosím o informaci zda výše uvedený postup pomohl, nebo zda je problém stále aktuální. Děkuji

**Comment by MilanFrybert** [comment]
Uzavírám issue - zákazník dále nekomunikuje.
